---
layout: post
title:  "Java线程的停止"
categories: "Java"
tags: "java Thread"
author: "songzhx"
date:   2019-02-01 10:05:00
---

 Java中有以下3种方法可以终止正在运行的线程

1. 使用退出标志，使线程正常退出，也就是当run方法完成后线程终止。
2. 使用stop方法强行终止线程，但是不推荐使用这个方法，因为stop和suspend及resume一样，都是作废过期的方法，使用它们可能产生不可预料的结果。
3. 使用interrupt方法中断线程。



## 1. 使用interrupt方法中断线程

>this.interrupted()：测试当前线程是否已经是中断状态，执行后具有将状态标志置清除为false的功能。
>
>this.isInterrupted():测试线程Thread对象是否已经是中断状态，但不清除状态标志。



```java
package exthread;

public class MyThread extends Thread {
	@Override
	public void run() {
		super.run();
		for (int i = 0; i < 500000; i++) {
			if (this.interrupted()) {
				System.out.println("已经是停止状态了!我要退出了!");
				break;
			}
			System.out.println("i=" + (i + 1));
		}
	}
}


package test;

import exthread.MyThread;

import exthread.MyThread;

public class Run {

	public static void main(String[] args) {
		try {
			MyThread thread = new MyThread();
			thread.start();
			Thread.sleep(2000);
			thread.interrupt();
		} catch (InterruptedException e) {
			System.out.println("main catch");
			e.printStackTrace();
		}
		System.out.println("end!");
	}

}

```

<img src="https://tva1.sinaimg.cn/large/006y8mN6gy1g6fcrdye3dj309w0ewq3f.jpg" alt="image-20190325101948903" style="zoom:75%;" />

## 2.使用异常法中断线程

上面的事例虽然停止了线程，但如果for语句下面还有语句，还是会继续运行的。

下面通过异常法解决这个问题。

**使用异常法中断线程**

```java
package exthread;

public class MyThread extends Thread {
	@Override
	public void run() {
		super.run();
		try {
			for (int i = 0; i < 500000; i++) {
				if (this.interrupted()) {
					System.out.println("已经是停止状态了!我要退出了!");
					throw new InterruptedException();
				}
				System.out.println("i=" + (i + 1));
			}
			System.out.println("我在for下面");
		} catch (InterruptedException e) {
			System.out.println("进MyThread.java类run方法中的catch了！");
			e.printStackTrace();
		}
	}
}
package test;

import exthread.MyThread;

public class Run {

	public static void main(String[] args) {
		try {
			MyThread thread = new MyThread();
			thread.start();
			Thread.sleep(2000);
			thread.interrupt();
		} catch (InterruptedException e) {
			System.out.println("main catch");
			e.printStackTrace();
		}
		System.out.println("end!");
	}

}

```

结果：

<img src="https://tva1.sinaimg.cn/large/006y8mN6gy1g6fcrimufuj31260d4wfo.jpg" alt="image-20190325101830384" style="zoom: 67%;" />



## 3.使用stop方法中断线程

```java
package testpackage;

public class MyThread extends Thread {
	private int i = 0;

	@Override
	public void run() {
		try {
			while (true) {
				i++;
				System.out.println("i=" + i);
				Thread.sleep(1000);
			}
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
package test.run;

import testpackage.MyThread;

public class Run {

	public static void main(String[] args) {
		try {
			MyThread thread = new MyThread();
			thread.start();
			Thread.sleep(8000);
			thread.stop();
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
```

实验结果：

<img src="https://tva1.sinaimg.cn/large/006y8mN6gy1g6fcrj68m7j30zm09sgm8.jpg" alt="image-20190325104647925" style="zoom: 67%;" />

​	调用stop()方法时会抛出java.lang.ThreadDeath异常，但在通常的情况下，此异常不需要显示的捕捉。

​	**使用stop()释放锁将会给数据造成不一致的结果。**如果出现这样的情况，程序处理的数据就可能遭到破坏，最终导致程序执行的流程错误，一定要特别注意。
